//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tuanna.Data.Ekmekcim
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ekmekcimnetEntities : DbContext
    {
        public ekmekcimnetEntities()
            : base("name=ekmekcimnetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLAltKategori> TBLAltKategori { get; set; }
        public virtual DbSet<TBLKategori> TBLKategori { get; set; }
        public virtual DbSet<TBLSiparis> TBLSiparis { get; set; }
        public virtual DbSet<TBLUrun> TBLUrun { get; set; }
        public virtual DbSet<TBLUye> TBLUye { get; set; }
        public virtual DbSet<TBLAnlikStok> TBLAnlikStok { get; set; }
        public virtual DbSet<TBLFirma> TBLFirma { get; set; }
        public virtual DbSet<TBLMahalle> TBLMahalle { get; set; }
        public virtual DbSet<TBLOdeme> TBLOdeme { get; set; }
        public virtual DbSet<TBLSehir> TBLSehir { get; set; }
        public virtual DbSet<TBLUrunAlim> TBLUrunAlim { get; set; }
        public virtual DbSet<TBLAnlikBakiye> TBLAnlikBakiye { get; set; }
        public virtual DbSet<TBLIletisim> TBLIletisim { get; set; }
    }
}
