//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tuanna.Data.Ekmekcim
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFirma
    {
        public int SatirNo { get; set; }
        public string FirmaAd { get; set; }
        public string Adres { get; set; }
        public string Sehir { get; set; }
        public string Tel { get; set; }
        public int IslemYapan { get; set; }
        public string IslemTarih { get; set; }
    }
}
