//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tuanna.Data.Ekmekcim
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLIletisim
    {
        public int SatirNo { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Mail { get; set; }
        public string Mesaj { get; set; }
        public string IslemTarih { get; set; }
        public bool Okundu { get; set; }
    }
}
