//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tuanna.Data.Ekmekcim
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMahalle
    {
        public int SatirNo { get; set; }
        public int Sehir { get; set; }
        public string MahalleAd { get; set; }
    }
}
