//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tuanna.Data.Ekmekcim
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLOdeme
    {
        public int SatirNo { get; set; }
        public int UyeFirma { get; set; }
        public int FisNo { get; set; }
        public string OdemeTip { get; set; }
        public string OdemeTarih { get; set; }
        public decimal OdemeTutar { get; set; }
        public string IslemTarih { get; set; }
        public int IslemYapan { get; set; }
    }
}
