//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tuanna.Data.Ekmekcim
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSiparis
    {
        public int SatirNo { get; set; }
        public int Uye { get; set; }
        public int Urun { get; set; }
        public int Adet { get; set; }
        public bool OnaylandiMi { get; set; }
        public bool GorulduMu { get; set; }
        public bool Teslimat { get; set; }
        public string IslemTarih { get; set; }
    }
}
