//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tuanna.Data.Ekmekcim
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLUye
    {
        public int SatirNo { get; set; }
        public string AdSoyad { get; set; }
        public bool Cinsiyet { get; set; }
        public string Cep { get; set; }
        public string Mail { get; set; }
        public int Mahalle { get; set; }
        public string Cadde { get; set; }
        public string ApartmanNo { get; set; }
        public string ApartmanAd { get; set; }
        public string DaireNo { get; set; }
        public string Sifre { get; set; }
        public bool OnayDurum { get; set; }
        public bool UyeDurum { get; set; }
        public string IslemTarih { get; set; }
    }
}
