//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tuanna.Data.Ekmekcim
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLUrun
    {
        public int SatirNo { get; set; }
        public int AltKategori { get; set; }
        public string UrunAd { get; set; }
        public decimal UrunFiyat { get; set; }
        public string UrunResim { get; set; }
        public bool UrunDurum { get; set; }
        public int IslemYapan { get; set; }
        public string IslemTarih { get; set; }
        public string Aciklama { get; set; }
        public Nullable<decimal> AlisFiyat { get; set; }
    }
}
