//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tuanna.Data.Ekmekcim
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLUrunAlim
    {
        public int SatirNo { get; set; }
        public int FisNo { get; set; }
        public int Firma { get; set; }
        public string Tarih { get; set; }
        public string Saat { get; set; }
        public string OdemeTip { get; set; }
        public int AlinanUrun { get; set; }
        public int AlinanMiktar { get; set; }
        public decimal AFiyat { get; set; }
        public decimal NetTutar { get; set; }
        public string IslemTarih { get; set; }
        public int IslemYapan { get; set; }
    }
}
